In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
data = pd.read_csv('air_quality_train.csv')
data = data.values
dfx = data[:,:5]
dfy = data[:,5]

In [15]:
print(dfx,dfy)

[[ 1.          0.29016495 -0.89871183 -0.37238147  0.44177059  0.52502448]
 [ 1.         -0.84270473 -0.15822922 -0.72365639 -0.99464217  0.59896038]
 [ 1.          0.23300381  0.15706968 -0.10209444  0.72994655 -0.20378187]
 ...
 [ 1.          1.0431652  -0.8532941   1.75476416 -1.79830858  0.44004223]
 [ 1.         -1.27708547  0.02207793  1.88059294 -1.0207355   0.74035908]
 [ 1.         -1.89374689 -0.80456069 -1.39187219  0.52221049  1.47960738]] [[ -82.15466656]
 [ -48.89796018]
 [  77.2703707 ]
 ...
 [-107.51050797]
 [ -47.34155781]
 [-115.93900296]]


In [4]:
dfx = np.array(dfx)
dfx = (dfx - dfx.mean(axis=0))/dfx.std(axis=0)
dfy = np.array(dfy)
dfx_new = np.ones((1600,6))
dfx_new[:,1:] = dfx
dfx=dfx_new
dfy = dfy.reshape(dfy.shape[0],1)
print(dfx.shape)

(1600, 6)


In [0]:
from sklearn.model_selection import train_test_split

In [0]:

X_train,X_test,Y_train,Y_test = train_test_split(dfx,dfy,test_size=0.2)

In [7]:
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

(1280, 6) (1280, 1) (320, 6) (320, 1)


In [8]:
print(X_train)

[[ 1.         -0.37354726  0.86804874  1.68419019 -1.10644773  0.82375033]
 [ 1.         -0.58167964 -0.90258188  0.43493718 -0.53429464 -1.5411321 ]
 [ 1.         -1.95951485 -0.15737927 -1.15350693  1.06474879  1.24315877]
 ...
 [ 1.          0.47127364  0.52356385  1.35051548  0.33345953 -0.15046594]
 [ 1.          3.29288456  0.79510464 -0.48477979 -1.34406415 -1.04215883]
 [ 1.         -1.66630244  1.06759736 -0.19294659 -1.53228511  1.30361634]]


In [0]:

def hypothesis(X,theta,Y):
  return np.dot(X,theta)-Y

In [0]:
def error(X,theta,Y):
  m = X.shape[0]
  h0 = hypothesis(X,theta,Y)
  error = ( np.sum(np.square(h0)) )/(2*m)
  return error

In [0]:

def grad(theta,X,Y):
  h0 = hypothesis(X,theta,Y)
  return np.dot(X.T,h0)

In [0]:
def grad_des(theta,X,Y,learning_rate=0.1):
 # print(theta,X,Y)
  m=X.shape[0]
  err_list=[]
  for itr in range(10000) :
    theta = theta - learning_rate*grad(theta,X,Y)/m
    err = error(X,theta,Y)
    print(err)
    err_list.append(err)
  return theta,err_list

In [22]:
theta = np.random.randn(6,1)
print(theta)

[[-1.51193068]
 [-0.26752725]
 [-2.90030607]
 [-0.87974089]
 [-1.7885379 ]
 [ 1.76856504]]


In [23]:
#theta = np.zeros((6,1))
print(theta.shape)
theta,err_list = grad_des(theta,X_train,Y_train)

(6, 1)
5329.460962481772
4356.289081276564
3568.197684342101
2929.908542512772
2412.8831957985503
1994.032344698005
1654.672970326778
1379.685516852007
1156.8326642318439
976.208635709742
829.7939676437265
711.0954967831842
614.8552158079744
536.8147921414604
473.52508307815714
422.19202928540307
380.551963202091
346.770704930047
319.36189731910906
297.1209036294793
279.0712953822766
264.4215270286768
252.52985390146426
242.87592156163623
235.03775506884193
228.67311957320794
223.50441999717287
219.30646637225465
215.89655982371133
213.12645807690313
210.8758633954635
209.04714385274082
207.56105385479245
206.35326435697147
205.37154925263135
204.57350358317098
203.92469283455281
203.39715170665332
202.96816622567303
202.61928560978092
202.3355204551361
202.10469203723602
201.91690418839525
201.76411461321212
201.63978688063412
201.53860787835902
201.45625839039334
201.3892267892339
201.334657723651
201.290229215106
201.25405281819624
201.22459250807657
201.20059877503292
201.181055069

In [0]:
Y_pred = hypothesis(X_train,theta,Y_train) + Y_train

In [0]:
def coeff_of_det(YA,YP):
  temp = (YA-YP)*(YA-YP)/((YA-YA.mean(axis=0))*(YA-YA.mean(axis=0)))
  return 1-temp

In [18]:
R = coeff_of_det(Y_train,Y_pred)
print(R,R.shape)

[[ 0.89480306]
 [ 0.9939219 ]
 [-2.2666429 ]
 ...
 [ 0.97982832]
 [ 0.99863645]
 [ 0.69044573]] (1280, 1)


In [19]:
print(min(R),max(R))

[-6.7437117e+08] [1.]


In [20]:
print(R.mean())

-527493.548042225
